mixed-port: 7890
allow-lan: true
mode: rule
log-level: info
unified-delay: true
tcp-concurrent: true

proxies:

proxy-groups:
  - name: Proxy
    type: select
    proxies:
      - DIRECT


rules:
  - MATCH,Proxy
