name: JSON Proxy To Mihomo Auto Convert
on:
  push:
    branches: [ main ]
  schedule:
    - cron: '0 */2 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  convert:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install Dependencies
        run: pip install requests

      - name: Run JSON Convert Script
        run: python json2mihomo.py

      - name: Check & Commit Changes
        run: |
          git config --global user.name "Mihomo-Auto-Bot"
          git config --global user.email "bot@github.com"
          git add mihomo_all_json_config.yaml
          # 无变更直接退出，不报错
          if git diff --staged --quiet; then
            echo "No changes to commit, exit success"
            exit 0
          fi
          git commit -m "Auto update from all.json | GitHub Actions"
          git push
